### ISSUE TITLE
support for filtering out incompatible scales in configuration file

### ISSUE THREAD

**Issue by boegel** [EESSI/test-suite#100]
On some systems, specific scales like `1_cpn_2_nodes` don't make sense because the system simply doesn't allow using partial nodes when requested multiple nodes.

This is the case on Snellius @ SURF, where submitting a job that asks for 2 GPUs on 2 different nodes doesn't work.

Ideally, there is a way to express that `1_cpn_2_nodes` should never be used on Snellius through the configuration file.

cfr. discussion in https://github.com/EESSI/test-suite/pull/54#discussion_r1451741808

**Comment by casparvl** [comment]
In the config:
```
scales = {s: SCALES[s] for s in SCALES if s not in ['1_cpn_2_nodes']}
```
and some hook
``` 
filter_scales():
    features += '+self.scale'
```

**Comment by casparvl** [comment]
See https://github.com/EESSI/test-suite/pull/111
