### ISSUE TITLE
Running CUDA modules on pure `cpu` partitions

### ISSUE THREAD

**Issue by satishskamath** [EESSI/test-suite#101]
## Context
Some applications that are compiled with CUDA run on pure `cpu` partitions without complaints such as GROMACS but some applications such as OSU (https://github.com/EESSI/test-suite/pull/54) require `libcuda.so.1` which their binaries are linked to. An argument for this was that we can link it with stubs `libcuda.so.1` if the normal one is not found using `LD_LIBRARY_PATH`. 

## Problems
* Can a `cuda` feature be defined at the partition level?
* Is it possible to selectively pass an environment variable for a few partitions only?

## Potential solutions
* We have a CUDA feature already defined for the 1st problem.
* The second problem can be sorted by adding this as a part of the launcher statement such as `mpirun -x `.

**Comment by satishskamath** [comment]
Potential solutions are not working on `cpu` partitions on Snellius. Due to a common GPFS, the CUDA module is currently finding `libcuda.so.1` and failing with this error:
```
[../../../util/osu_util_mpi.c:3030] CUDA call 'cudaGetDeviceCount(&dev_count)' failed with 100: no CUDA-capable device is detected
[../../../util/osu_util_mpi.c:3030] CUDA call 'cudaGetDeviceCount(&dev_count)' failed with 100: no CUDA-capable device is detected
--------------------------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code. Per user-direction, the job has been aborted.
--------------------------------------------------------------------------
--------------------------------------------------------------------------
mpirun detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

```

**Comment by satishskamath** [comment]
> Potential solutions are not working on `cpu` partitions on Snellius. Due to a common GPFS, the CUDA module is currently finding `libcuda.so.1` and failing with this error:
> 
> ```
> [../../../util/osu_util_mpi.c:3030] CUDA call 'cudaGetDeviceCount(&dev_count)' failed with 100: no CUDA-capable device is detected
> [../../../util/osu_util_mpi.c:3030] CUDA call 'cudaGetDeviceCount(&dev_count)' failed with 100: no CUDA-capable device is detected
> --------------------------------------------------------------------------
> Primary job  terminated normally, but 1 process returned
> a non-zero exit code. Per user-direction, the job has been aborted.
> --------------------------------------------------------------------------
> --------------------------------------------------------------------------
> mpirun detected that one or more processes exited with non-zero status, thus causing
> the job to be terminated. The first process to do so was:
> ```

This is happening because of `D D` option which was added to all pt2pt tests by the `hpctestlib`. This is now mitigated.

Currently going with the a export statement for `LD_LIBRARY_PATH` as the environment variable in the script. Once that is tested this issue can be closed.

**Comment by satishskamath** [comment]
Exporting `LD_LIBRARY_PATH` solution is working on Snellius. Once others confirm, this issue can be closed.

**Comment by casparvl** [comment]
As discussed in the meeting, we opt for just disabling testing CUDA-based modules on CPU nodes. We will do that by altering [this](https://github.com/EESSI/test-suite/blob/daa3aff097573ba498c4e06c4f78b2d7b1d10378/eessi/testsuite/hooks.py#L286) with a 
```
elif not is_cuda_module and required_device_type == DEVICE_TYPES[CPU]:
    valid_systems = f'+{FEATURES[CPU]}'
elif is_cuda_module and required_device_type == DEVICE_TYPES[CPU]:
    valid_systems =  ''
```

**Comment by satishskamath** [comment]
I think it is still not as trivial as the above mentioned code. Reason: You still want to perform `cpu` tests on `gpu` nodes using `CUDA` modules. In this case device type would still be `cpu`. In my opinion, this is better:
```
       elif not is_cuda_module and required_device_type == DEVICE_TYPES[CPU]:
        # Using the CPU requires partitions with FEATURES[CPU] feature
        # Note: making FEATURES[CPU] an explicit feature allows e.g. skipping CPU-based tests on GPU partitions
        valid_systems = f'+{FEATURES[CPU]}'

    elif is_cuda_module and required_device_type == DEVICE_TYPES[CPU]:
        # Note: This applies for CUDA module tests that want to test only on cpus on gpu partitions.
        valid_systems = f'+{FEATURES[CPU]} +{FEATURES[GPU]} %{GPU_VENDOR}={GPU_VENDORS[NVIDIA]}'

```

**Comment by casparvl** [comment]
So basically you're saying: we have two variables (is this a cuda module, and which device type is requested) and _all_ 4 combinations of these should essentially be treated seperately?

The one thing to realize is that 

```
 valid_systems = f'+{FEATURES[CPU]} +{FEATURES[GPU]} %{GPU_VENDOR}={GPU_VENDORS[NVIDIA]}'
```
will mean a test only runs if someone sets `CPU` as feature for their partition. That means they will run _all_ CPU-based test (i.e. including e.g. a pure CPU run of GROMACS). I actually agree that your scenario is a bit of an exception: which test has a CUDA modules, requires a CPU device type, and _still makes sense_? I guess OSU host-host is something you _always_ want to run, also when people did _not_ declare their partition explicitely as having the CPU feature...

I'm wondering if for OSU we should make an exception and just not use the hook. For OSU, we could simply do:

```
@run_after('init')
is_cuda_module = is_cuda_required_module(test.module_name)
if is_cuda_module:
        self.valid_systems = [f'+{FEATURES[GPU]} %{GPU_VENDOR}={GPU_VENDORS[NVIDIA]}']
else:
       self.valid_systems = [+{FEATURES[CPU]]
```
or something? I'm not sure if this would lead to the behaviour we want, but I guess so (for a CUDA module, run only on GPU-capable nodes, but run both the GPU-GPU and host-host communication tests. For non-CUDA modules, only run on systems that have the CPU feature and only generate host-host tests).

**Comment by satishskamath** [comment]
> So basically you're saying: we have two variables (is this a cuda module, and which device type is requested) and _all_ 4 combinations of these should essentially be treated seperately?
> 
> The one thing to realize is that
> 
> ```
>  valid_systems = f'+{FEATURES[CPU]} +{FEATURES[GPU]} %{GPU_VENDOR}={GPU_VENDORS[NVIDIA]}'
> ```
> 
> will mean a test only runs if someone sets `CPU` as feature for their partition. That means they will run _all_ CPU-based test (i.e. including e.g. a pure CPU run of GROMACS). I actually agree that your scenario is a bit of an exception: which test has a CUDA modules, requires a CPU device type, and _still makes sense_? I guess OSU host-host is something you _always_ want to run, also when people did _not_ declare their partition explicitely as having the CPU feature...

But this is what we intend, correct? If someone wants to run `cpu` based tests on their `gpu` partition with the `CUDA` module, they should declare `cpu` as a feature for the gpu partition along with `gpu` (as a feature) in their config file and if `cpu` is a feature, then `cpu` tests should run on them, no matter what the application. I am trying to think of an application where this does not apply. Is there a pure `cpu` based test in GROMACS, that should not/cannot run on the `gpu` partition?

**Comment by casparvl** [comment]
Fixed by https://github.com/EESSI/test-suite/pull/110
