### ISSUE TITLE
add support for specifying GPU vendor in configuration

### ISSUE THREAD

**Issue by smoors** [EESSI/test-suite#34]
with feature `cuda` we can more explicitly filter on devices that support cuda (required for tests that use a cuda module on a gpu).

later on, we more easily add `rocm` and `oneapi` when AMD and Intel GPU modules become available in EESSI.

**Comment by smoors** [comment]
we could even go a step further and add partition `extras`, so we can filter on supported cuda versions, e.g.
```
'partitions': [
    ...,
    'extras': {
        'min_cuda_version': '9.1.85',
        'max_cuda_version': '11.7.0',
    },
],
```
https://reframe-hpc.readthedocs.io/en/stable/config_reference.html#config.systems.partitions.extras
https://reframe-hpc.readthedocs.io/en/stable/regression_test_api.html#reframe.core.systems.SystemPartition.extras

**Comment by smoors** [comment]
the alternative is to filter based on the device architecture, e.g.
```
'partitions': [
    'name': 'pascal_gpu',
    ...,
    'devices': {
        'type': 'gpu',
        'arch': 'nvidia:pascal',
        'num_devices': 2,
    },
],
```

- advantage: features are no longer needed, as all necessary info is present in the `devices` section. thus, the features can be used separately from the logic in the test: the test can by default run all combinations that are possible, and users can define features for custom filtering
- disadvantage: we have to create and maintain a GPU database

**Comment by boegel** [comment]
Problem with using `devices` solution is that we can prevent tests from being generated, we can only skip them afterwards.

1st suggestion using `features` + `extras` seems like a better approach.

Candidate entries for `features`:
* `gpu`
* vendor: `nvidia` or `amd` or `intel`
* capabilities: `cuda` or `rocm` or `openacc` or `hip` or `sycl`
  * these probably need to be specified by the test, to let the `filter_tests_by_device_type` hooks determine whether the test can run?

Candidate entries for `extras`:
* GPU model (like `a100`)
* number of GPUs (`num_devices`)
* min./max. support CUDA version
* CUDA compute capability (like`cc-8.0`)
