### ISSUE TITLE
reframe.log and reframe.out contents get overwritten

### ISSUE THREAD

**Issue by laraPPr** [EESSI/test-suite#40]
The contents of the reframe.log file and reframe.out file get overwritten with every run by reframe. 

Currently keeping the logs and outputs of different runs by changing the names of the files manually.

**Comment by smoors** [comment]
you can add a `timestamp` to the log files in the config file, that will be added to the log file.
for example, this is what i have for my local tests:
```
            'handlers': [
                {
                    'type': 'file',
                    'name': os.path.join(os.getenv('RFM_OUTPUT_DIR', os.curdir), 'logs', 'reframe.log'),
                    'level': 'debug',
                    'format': '[%(asctime)s] %(levelname)s: %(check_name)s: %(message)s',  # noqa: E501
                    'append': False,
                    'timestamp': "%Y%m%d_%H%M%S",
                },
```

the log file then becomes `reframe_20230520_015924.log`

**Comment by boegel** [comment]
I think it makes sense to use `'append': True` in our example configuration files, overwriting by default is kinda evil?
