### ISSUE TITLE
wrong number of MPI ranks when running multi-node jobs with vsc_hortense config

### ISSUE THREAD

**Issue by smoors** [EESSI/test-suite#61]
the problem is in the `mympyrun` wrapper.
the `--hybrid` option expects as value the number of tasks per node instead of total number of tasks.

```
@register_launcher('mympirun')
class MyMpirunLauncher(JobLauncher):
    def command(self, job):
        return ['mympirun', '--hybrid', str(job.num_tasks)]
```

replacing job.num_tasks with job.num_tasks/job.num_nodes

possible solutions: replace `--hybrid job.num_tasks` with
-  `--hybrid job.num_tasks_per_node` --> i checked that this indeed fixes the job script
- `--universe job.num_tasks`
- `--mpirunoptions="-np job.num_tasks"`

**Comment by boegel** [comment]
Hmm, is this really fixed by #80?
