### ISSUE TITLE
avoid duplicate (and inconsistent) logging settings in configuration files

### ISSUE THREAD

**Issue by boegel** [EESSI/test-suite#64]
* `from common_config import common_logging_config`
* `'logging': common_logging_config,` in configuration files
* add comments to explain difference between `reframe.log` and `reframe.out`, etc.

**Comment by casparvl** [comment]
I had an hourly run of the test suite over the weekend on Vega, and noticed something annoying: the `handlers:  ... type: 'file'...` logger writes its logfile to the current dir by default. As a result, I had about 60-odd log files in the root of my homedir.

Especially for the CI stuff, I would like _everything_ (_all_ logging, stagedirs, output) to end up in the same prefix. I can quite easily do that with something like:

```
# Get username of current user
homedir = environ.get('HOME')

# This config will write all staging, output and logging to subdirs under this prefix
reframe_prefix = f'{homedir}/reframe_runs'
log_prefix = f'{home_prefix}/logs'

# ReFrame complains if the directory for the file logger doesn't exist yet
makedirs(f'{log_prefix}', exist_ok=True)
...
    'systems': [
...
            'prefix': reframe_prefix,
...
    'logging': [
...
            'handlers': [
...
                    'type': 'file',
                    'name': f'{log_prefix}/reframe.log',
...
            'handlers_perflog': [
...
                    'type': 'filelog',
                    'prefix': f'{log_prefix}/%(check_system)s/%(check_partition)s',
```

I _think_ this will also work with some `common_logging_config`, as we can probably overwrite _only_ the `name` (for the `file` handler) and `prefix` (for the `filelog` perflog handler) in our own config then. 

Just wanted to remark that things like the prefixes may be system-specific, but I think those can still work fine together with some common logging settings which determine _which_ logs will be created (i.e. which types, at which log level, etc).

**Comment by smoors** [comment]
created an issue in ReFrame for adding support for `$RFM_LOG_DIR` envar, to make this easier.
https://github.com/reframe-hpc/reframe/issues/2969

**Comment by smoors** [comment]
hard-coding `log_prefix` in the config file or in `common_logging_config` is actually not necessary to have everything stored in the prefix.

with `--prefix prefix_path`, the `stage`, `output`, and `perflog` dirs are saved in prefix_path.
with `--save-log-files`, all ReFrame file logs are copied into `prefix_path/output`.
